/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package R18_G2_ASM2;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws Exception
    {
        MovieSystem system = new MovieSystem();
        system.run();
    }
}